Update report docs
nethesis/nethvoice-docs pull request #98
Opened 2021-01-19 13:11 UTC by andre8244

Expand NethVoice report documentation

2021-01-19 14:36 UTC, gsanchietti commented on admin-manual/report.rst
> +Per motivi di leggibilità alcuni grafici mostrano soltanto i dati più rilevanti: il pulsante :guilabel:`Mostra dettagli` è possibile accedere al set completo dei dati del grafico.
```suggestion
Per motivi di leggibilità, alcuni grafici mostrano soltanto i dati più rilevanti: attraverso il pulsante :guilabel:`Mostra dettagli` è possibile accedere al set completo dei dati del grafico.
```

2021-01-20 13:17 UTC, edospadoni approved these changes

2021-01-20 13:32 UTC, gsanchietti requested changes

2021-01-20 13:32 UTC, gsanchietti commented on admin-manual/report.rst
> +le impostazioni sono organizzate nelle seguenti sezioni:
```suggestion
Le impostazioni sono organizzate nelle seguenti sezioni:
```

2021-01-20 13:32 UTC, gsanchietti commented on admin-manual/report.rst
> +- Configurare un nuovo prefisso di destinazione, indicando il prefisso nazionale spagnolo (`0034` oppure `+34`, in funzione di come è stato configurato il centralino) e selezionando `Spagna` come des
```suggestion
- Configurare un nuovo prefisso di destinazione, indicando il prefisso nazionale spagnolo (`0034` oppure `+34`, in funzione di come è stato configurato il centralino) e selezionare `Spagna` come destinazione
```

2021-01-20 13:44 UTC, gsanchietti commented on admin-manual/report.rst
> +- Configurare un nuovo prefisso di destinazione, indicando il prefisso nazionale spagnolo (`0034` oppure `+34`, in funzione di come è stato configurato il centralino) e selezionando `Spagna` come des
Let's keep original form

2021-01-20 14:19 UTC, gsanchietti approved these changes

2021-01-20 14:27 UTC, merged